# Generated by Django 3.0.3 on 2020-03-19 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modshop', '0004_auto_20200318_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='id_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modshop.Goods'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
