# Generated by Django 3.0.3 on 2020-03-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modshop', '0005_auto_20200319_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
