# Generated by Django 3.0.3 on 2020-03-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modshop', '0007_auto_20200320_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
